#!/usr/bin/env python3
"""PPT Skill - Generate PowerPoint presentations from structured data."""

import json
import sys
import os
from pathlib import Path


def generate_ppt(title: str, slides: list, output_path: str) -> dict:
    """
    Generate a PowerPoint presentation.

    Args:
        title: Presentation title
        slides: List of slide objects, each with:
               - type: "title" | "content" | "bullet" | "image"
               - title: slide title
               - content: slide content text
        output_path: Where to save the .pptx file
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        return {
            "status": "error",
            "output": "python-pptx not installed. Run: pip install python-pptx",
            "error": "ModuleNotFoundError: python-pptx"
        }

    try:
        prs = Presentation()

        # Title slide
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_placeholder = title_slide.shapes.title
        subtitle_placeholder = title_slide.placeholders[1]
        title_placeholder.text = title
        subtitle_placeholder.text = "Generated by PPT Skill v1.0.0"

        # Content slides
        for slide_data in slides:
            slide_type = slide_data.get("type", "content")
            slide_title = slide_data.get("title", "")
            slide_content = slide_data.get("content", "")

            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = slide_title

            if slide_content:
                body = slide.placeholders[1]
                tf = body.text_frame
                tf.text = slide_content

        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        prs.save(output_path)

        return {
            "status": "success",
            "output": f"Presentation saved to {output_path} ({len(slides)} slides)",
            "error": None
        }
    except Exception as e:
        return {
            "status": "error",
            "output": None,
            "error": str(e)
        }


def main():
    if len(sys.argv) < 2:
        result = {"status": "error", "output": None, "error": "No input provided"}
        print(json.dumps(result))
        sys.exit(1)

    try:
        params = json.loads(sys.argv[1])
    except json.JSONDecodeError as e:
        result = {"status": "error", "output": None, "error": f"Invalid JSON: {e}"}
        print(json.dumps(result))
        sys.exit(1)

    title = params.get("title", "Untitled Presentation")
    slides = params.get("slides", [])
    output_path = params.get("output_path", "output.pptx")

    result = generate_ppt(title, slides, output_path)
    print(json.dumps(result))


if __name__ == "__main__":
    main()
